### PR TITLE
Updates for Draft release 1.1.0, Sync Test to Stage

### PR DESCRIPTION
**Pull request by cdcabrera**
## Description
Environment sync

### Features
1. **inventoryList** issues/414 RBAC for inventory links (#446) (81a391f)

### Bug Fixes
1. **openshiftView,rhelView** issues/414 inventory link prefix (#463) (eeda4a8)
1. **userSelectors** issues/414 RBAC perms for inventory links (#465) (c9c2ce9)

### Performance Improvements
1. **authentication** issues/414 restructure permissions (#446) (216b34a)

### Bug Fixes
1. **platformServices** issues/473 apply hideGlobalFilter (#474) (cfd6ded)

## Cloud Provider Commit Additions
Delayed...
### Bug Fixes
1. ~**locale** issues/389 virtual to virtualized string (#463) (c6f4d38)~
1. ~**inventoryList** issues/389 display cloud providers (#467) (1942cec)~
1. ~**helpers,testing** noopTranslate, helpful test snapshots (#469) (0f88870)~
1. ~**openshiftView,rhelView** issues/468 header names (#469) (d927886)~

## Notes
- Adds commits for RBAC detection enable/disable for inventory links.
- ~Per team discussion updates for Cloud Provider are now included. If needed we can roll them off the end of this PR and merge the original commits~ @ntkathole

### CODE REVIEW

**Review by ntkathole — APPROVED** [review]
ACK :+1:

**Review by jlprevatt — APPROVED** [review]
Evaluated items for doc impact, approving.

**Comment by cdcabrera** [comment]
- As of 10/23 we rolled back the cloud provider updates. 
- Travis appears to not be push changes in a timely fashion, however the rolled back commits are actively in QA now
- We'll be adding a SAP disable commit to this PR

**Comment by ntkathole** [comment]
@cdcabrera As of 26/10, commits looks good. ACK!

**Comment by cdcabrera** [comment]
@ntkathole took another look. Still unable to recreate the issue, had the design team also take a look in case it was my machine and browser, no luck.

Since the filter "may or may not" be broken regardless of whether we push code we'll keep an eye out and continue on plan with the caveat of "we may stop at prod-beta" to see if anything detrimental is popping up

**Comment by ntkathole** [comment]
@cdcabrera ACK :+1:

**Pull request merged**
