### PR TITLE
Draft release 1.2.0, Sync Test to Stage

### PR DESCRIPTION
**Pull request by cdcabrera**
## Notes
Cloud provider updates

### Bug Fixes

* **build:** npm updates ([#484](https://github.com/RedHatInsights/curiosity-frontend/issues/484)) ([fb001dd](https://github.com/RedHatInsights/curiosity-frontend/commit/fb001dd4b23a2bace25a7f6cd9b33e5ee24909e4))
* **helpers,testing:** noopTranslate, helpful test snapshots ([#469](https://github.com/RedHatInsights/curiosity-frontend/issues/469)) ([7b350c1](https://github.com/RedHatInsights/curiosity-frontend/commit/7b350c1b02c4fdd735196b0f5fd7031eac7bf3af))
* **inventoryList:** issues/389 display cloud providers ([#467](https://github.com/RedHatInsights/curiosity-frontend/issues/467)) ([b3749a4](https://github.com/RedHatInsights/curiosity-frontend/commit/b3749a4ee958b0ba68bc17011b08075016502b84))
* **inventoryList:** issues/468 display measurementType ([#485](https://github.com/RedHatInsights/curiosity-frontend/issues/485)) ([c4dbf52](https://github.com/RedHatInsights/curiosity-frontend/commit/c4dbf52af268bbf45b4d48b1758221e4bce8c3b4))
* **locale:** issues/389 virtual to virtualized string ([#463](https://github.com/RedHatInsights/curiosity-frontend/issues/463)) ([12df0ae](https://github.com/RedHatInsights/curiosity-frontend/commit/12df0ae16879e1fe541b6dda6db05f6949467b9d))
* **locale:** issues/481 add cloud provider string ([#482](https://github.com/RedHatInsights/curiosity-frontend/issues/482)) ([ad767af](https://github.com/RedHatInsights/curiosity-frontend/commit/ad767af81f48f17d24850d68cfe8088752d4a757))
* **openshiftView,rhelView:** issues/468 header names ([#469](https://github.com/RedHatInsights/curiosity-frontend/issues/469)) ([87d0793](https://github.com/RedHatInsights/curiosity-frontend/commit/87d0793da5d9d1cbc83ec6c3afb19f7bd77c53e4))
* **openshiftView,rhelView:** issues/468 sort measurementType ([#487](https://github.com/RedHatInsights/curiosity-frontend/issues/487)) ([c670525](https://github.com/RedHatInsights/curiosity-frontend/commit/c670525b0f8a6c708b18be0bd0066999562a4c31))

### Features

* **inventoryList,guestsList:** issues/494 fixed column widths ([#472](https://github.com/RedHatInsights/curiosity-frontend/issues/472)) ([9aa6902](https://github.com/RedHatInsights/curiosity-frontend/commit/9aa690203a0f7e52a98864c5e133b220772e43fe))

### Bug Fixes
* **inventoryList:** issues483 column header subscribed copy ([#497](https://github.com/RedHatInsights/curiosity-frontend/issues/497)) ([c837279](https://github.com/RedHatInsights/curiosity-frontend/commit/c8372794c0ff2f2acb99886138fb6d86fb15c60f))
* **table:** issues/494 check title prop is defined ([#496](https://github.com/RedHatInsights/curiosity-frontend/issues/496)) ([e91a4e7](https://github.com/RedHatInsights/curiosity-frontend/commit/e91a4e736524bc351562e3742d363786e7cbb145))

### Features
* **bannerMessages:** issues/502 app messages ([#503](https://github.com/RedHatInsights/curiosity-frontend/issues/503)) ([08ccf16](https://github.com/RedHatInsights/curiosity-frontend/commit/08ccf16096cd354b8b05a4bf6ce000b2bf7ce315))
* **bannerMessages:** issues/502 cloud meter messaging ([#503](https://github.com/RedHatInsights/curiosity-frontend/issues/503)) ([fd2b36e](https://github.com/RedHatInsights/curiosity-frontend/commit/fd2b36e3e4a202bf316c609561c9f57fc8473ffa))
* **pageMessages:** issues/502 section for messaging ([#503](https://github.com/RedHatInsights/curiosity-frontend/issues/503)) ([8e6f96e](https://github.com/RedHatInsights/curiosity-frontend/commit/8e6f96e4175929f881ee3bf6620947ae672b6ae1))

### Bug Fixes
* **bannerMessages:** issues/511 limit activation to current date ([#513](https://github.com/RedHatInsights/curiosity-frontend/issues/513)) ([e1d818b](https://github.com/RedHatInsights/curiosity-frontend/commit/e1d818b6b77c232250f265fa9933ab389cce26c1))
* **inventoryList:** issues/492 set minHeight on first, last page ([#507](https://github.com/RedHatInsights/curiosity-frontend/issues/507)) ([ae2b76a](https://github.com/RedHatInsights/curiosity-frontend/commit/ae2b76aba681639e5f3c3c0418748640963daabb))
* **minHeight:** issues/501 restructure resize event ([#507](https://github.com/RedHatInsights/curiosity-frontend/issues/507)) ([baa1dbe](https://github.com/RedHatInsights/curiosity-frontend/commit/baa1dbe777236420507bddfa65e4684eb501c61d))
* **openshiftView,rhelView:** issues/492 increase per-page results ([#507](https://github.com/RedHatInsights/curiosity-frontend/issues/507)) ([579beae](https://github.com/RedHatInsights/curiosity-frontend/commit/579beae5083d22092995efb9b912691a4d92d327))

### Performance Improvements

* **openshiftView,rhelView:** simplify displayName callback ([#507](https://github.com/RedHatInsights/curiosity-frontend/issues/507)) ([22fa2ed](https://github.com/RedHatInsights/curiosity-frontend/commit/22fa2ed77e2a0af8273c4e47edb0a69bceba18c7))
* **rhsmServices,userServices:** expose cancel options ([#513](https://github.com/RedHatInsights/curiosity-frontend/issues/513)) ([d784aaf](https://github.com/RedHatInsights/curiosity-frontend/commit/d784aafb5aca082d6ba04c980740abee961c5700))

### Bug Fixes
- **bannerMessages** issues/511 copy update (#518) (8553e83)
- **bannerMessages** issues/511 apply query filter (#518) (ad20cf7)

### CODE REVIEW

**Comment by cdcabrera** [comment]
Current proposed release schedule

- Current merge date for this PR is planned for EST 11-03-2020
- A subsequent PR will be opened immediately once this PR is merged aiming to have this set of changes merged into Prod-stable EST 11-04-2020

**Comment by cdcabrera** [comment]
#488 is a blocking issue

**Comment by ntkathole** [comment]
@cdcabrera As openshift "total" type isse is resolved, consider my ACK for this release (without cloudmeter changes as of 11/111/2020).

**Comment by cdcabrera** [comment]
As of 20201117 a release delay towards Dec 2nd had been purposed, we'll review removing the blocked status on this PR the week of Dec 2nd

**Comment by cdcabrera** [comment]
The release plan as of 20201130 is to do an immediate PR for release 1.2.0 after this PR merges.

**Review by ntkathole — APPROVED** [review]
Looks good. ACK for this release.

**Pull request merged**
