### PR TITLE
Production Release 2.5.0

### PR DESCRIPTION
**Pull request by cdcabrera**
## Notes
- This release SHOULD BE prefixed by committing `CHANGELOG.md` and `package.json changes` on `main`, then tagging the last commit in `main` with a `v2.4.0` tag. This will in term generate the release process that creates this release as, most likely, `v2.5.0`

### Features
1. **toolbarFieldBillingProvider** ent-4689 select, services (#893) (d20e748)
1. **rhosak** ent-4689 activate billing provider (#894) (3d77b73)

### Bug Fixes
1. **rhosak** ent-4689 convert non-metric (#893) (1c6e9ca)
1. **toolbarFieldBillingProvider** ent-4689 tally query (#894) (eb3fd5c)
1. **rhosak** ent-4689 none, unknown billing provider (#936) (b7e402c)
1. **rhosak** ent-4982 storage GiB as GB hours to months (#934) (ed720da)
1. **i18n** ent-5022 allow empty string context value (#939) (d35a952)
1. **inventoryCard** ent-5022 pass meta response for configs (#939) (92c1eb4)
1. **rhosak** ent-5022 subscription type column activated (#939) (8b1b943)
1. **rhosak** ent-4982 storage GiB as GB hours to months (#943) (f01892d)
1. **rhosak** ent-4982 activate sort, storage GiB months (#945) (7964fa3)
1. **rhsmTransformers** ent-5121 hide graph future dates (#948) (3f6b5f1)

### Builds
1. **dev,proxy,prod** remove unused html template (#937) (7cf4da1)

### Code Refactoring
1. **authentication** ent-4899 align hook components (#921) (334fd25)
1. **bannerMessages** ent-4899 align hook components (#926) (cae6015)
1. **inventoryCardSubscriptions** ent-5129 camel to snake (#949) (e766075)

### Chores
1. **deps** bump codecov/codecov-action from 2.1.0 to 3.1.0 (#929) (2566541)
1. **build** ephemeral envs onboarding (#928) (cc5f6cf)
1. **build** npm updates (#930) (adf6ddc)
1. **build** ephemeral env frontend.yaml (#932) (af5ed9a)
1. **build** move ephemeral scripts to deploy dir (#935) (c6f6c87)
1. **testing** ephemeral envs, skip dist check (#937) (fa5f3f4)
1. **testing** allow skipping individual tests (#937) (ad9d79d)

### CODE REVIEW

**Comment by cdcabrera** [comment]
@mirekdlugosz @ntkathole @jlprevatt release to prod-stable is tentatively planned for the morning of 2022-07-11

**Comment by mirekdlugosz** [comment]
I am OK with that PR, but:

* I see it relies on "Storage-gibibyte-months" metric being available, and I think this will be introduced in next API prod deployment? So we should wait until after backend is updated.
* Do we want to include #955 ? I won't be able to test it on stage until August, but I don't want to block release.

**Comment by cdcabrera** [comment]
@mirekdlugosz 
- Agreed, this push should wait until the API is updated on prod with with `Storage-gibibyte-months`.
- And lets hold on merging in the "allow first dates" to prod-stable. We'll move it as far as we can, up to and including `prod-beta` dependent of course on `Storage-gibibyte-months` going to prod-stable first... there might be a chance both of those things go to `prod-stable` around the same time

**Review by mirekdlugosz — APPROVED** [review]
Turns out I checked what we have on prod on wrong place. "Storage-gibibyte-months" metric is already available, there's nothing stopping us from promoting that to prod-stable.

**Pull request merged**
