### PR TITLE
key-cycle

### PR DESCRIPTION
**Pull request by Jason-RH**
## What's included

...

## Example

...

### CODE REVIEW

**Comment by cdcabrera** [comment]
@Jason-RH @ryelo just need to update the commit message... to something like `chore(build): key-cycle`

**Comment by Jason-RH** [comment]
@cdcabrera I can update

**Comment by cdcabrera** [comment]
Just a heads up on behavior for the default/master/main branch. In order for it to push out it needs a "release" commit, default/master/main in our case heads straight to prod-stable. 

After @ryelo approves this PR may team can rebase it down to the other branches/environments, or you all can, and actually see the key update work... or if you want to run a release and push that commit to master we can go that route... rebasing is easier... just need to aim for

- `master` == prod-stable
- `stage` == prod-beta
- `qa` == stable environments
- `ci` == beta environments

**Review by ryelo — APPROVED** [review]

**Comment by ryelo** [comment]
@cdcabrera We're just taking care of merging it to the main branch and the app teams can merge it to the other places

**Review by cdcabrera — APPROVED** [review]

**Comment by ryelo** [comment]
@cdcabrera I'll let you merge

**Pull request merged**
