### PR TITLE
chore(build): run QE tests during PR workflow

### PR DESCRIPTION
**Pull request by san7ket**
The main goal is to run QE tests on ephemeral environment as part of PR workflow.

Right now there's one such tests that goes to subscription table and verifies it is not displayed. Later we will figure out how to create data inside ephemeral env, and we'll work on extending suite of tests.

I've got this running when issuing commands manually from my machine. Let's see if I can get it running from PR check as well.

### CODE REVIEW

**Comment by cdcabrera** [comment]
Just let me know when you want this merged @san7ket , everything looks good on the repo side

**Comment by san7ket** [comment]
@cdcabrera this fails in building curisoity-frontend, is this know issue ?

**Comment by san7ket** [comment]
We can merge this, even though some the tests would fail, which is WIP. We can test successful deployments on clowder until then

**Pull request merged**
