### PR TITLE
fix(build): issues/502 add recommendations link

### PR DESCRIPTION
**Pull request by cdcabrera**
## What's included

- fix(build): issues/502 add recommendations link

### Notes
- Activates the dotenv link for the banner recommendation
- @rblackbu @bclarhk 

### Proxy run check
1. update the NPM packages with `$ yarn`
1. make sure Docker is running, plus on network, then
1. `$ yarn start:proxy`
1. log in with an account that has mismatched Cloud Meter data, expecting the banner to be displayed
1. click on the link and confirm it navigates towards `https://access.redhat.com/subscription-watch-accuracy`

## Example

Screen Shot 2020-11-16 at 6 21 26 PM (2)

## Updates issue/story

#502

### CODE REVIEW

**Comment by cdcabrera** [comment]
As of 20201116 temporarily applying the blocked label to this since the link currently doesn't go anywhere.

**Review by bclarhk — DISMISSED** [review]
We'll likely edit the text once we have a writer with a working computer. ;-)

**Comment by rblackbu** [comment]
Copy update proposal prior to activating the link.

**Title:** Cloud provider mismatch
**Body:** There may be inconsistencies between data in the graph and your inventory display. The issue is currently being resolved.

**Comment by cdcabrera** [comment]
As of 20201202 we were expecting the copy and link to be active, since it is not we'll go ahead and direct this PR towards the CI branch

**Comment by cdcabrera** [comment]
Per @jlprevatt updates to copy requested

Original:
> There may be inconsistencies between data in the graph and your inventory display. The issue is currently being resolved.

Change 1
> "There may be" > "There might be" (Reason: "may" can mean "can" or "might" and the meaning can be misunderstood by ESL folks. Always use the more precise word, "can" or "might")

Change 2
> It would be better to more closely match the terms used in the GUI/doc for the graph and table. (The doc uses "usage and utilization graph" and shortens to "the graph" so I don't mind "graph" so much. But instead of "inventory" we should be using "current systems table.") So "...between the data in the graph and the current systems table."

Additional comment
> I had it pounded into my head to never promise the user a fix in writing. But if [the team approved this already], then I'll let it be.

**Comment by cdcabrera** [comment]
@ntkathole we're moving forward with getting this into QA in prep for an incremental push to prod-beta

**Comment by ntkathole** [comment]
> Per @jlprevatt updates to copy requested
> 
> Original:
> 
> > There may be inconsistencies between data in the graph and your inventory display. The issue is currently being resolved.
> 
> Change 1
> 
> > "There may be" > "There might be" (Reason: "may" can mean "can" or "might" and the meaning can be misunderstood by ESL folks. Always use the more precise word, "can" or "might")
> 
@jlprevatt this change should go into the document as well. Currently it say "There may be inconsistencies between data in the graph and your inventory display".

**Comment by ntkathole** [comment]
@cdcabrera 

- There is typo in message "**recommmend**"

- We are seeing only "View recommended actions to take in order to improve Subscription Watch reporting." message. The other message is not visible. 
"There might be inconsistencies between data in the graph and your current systems table. The issue is currently being resolved."
can you please confirm if following banner is expected ?

Screenshot from 2020-12-11 14-05-15

**Comment by jlprevatt** [comment]
@ntkathole Regarding your direct comment to me above, I was initially confused and thought you meant the product doc, but I think you mean the draft of the customer portal article. Yes, if the customer portal article directly quotes the on-screen messaging, the exact text of the message should appear there.

**Comment by cdcabrera** [comment]
Looks like we missed your ask @ntkathole ... 
> can you please confirm if following banner is expected ?

That is correct. The more verbose banner is the fallback for when the message has no link available. Now that the link is active this is expected

Screen Shot 2020-12-12 at 2 23 40 AM

**Pull request merged**
