### PR TITLE
Production Release 2.1.0

### PR DESCRIPTION
**Pull request by cdcabrera**
### Features

* **inventorySubscriptions:** ent-3352 activate subs table ([#795](https://github.com/RedHatInsights/curiosity-frontend/issues/795)) ([b8daecf](https://github.com/RedHatInsights/curiosity-frontend/commit/b8daecf89a2197a484f4e64c2cb36cf716f3b745))
* **productView,graphCard:** ent-4366 rhosak multi-graph display ([#824](https://github.com/RedHatInsights/curiosity-frontend/issues/824)) ([c8562bd](https://github.com/RedHatInsights/curiosity-frontend/commit/c8562bd58b06f46924c9f933b9495a9ee528c11e))
* **productView,inventoryList:** ent-4367 rhosak inventory ([#831](https://github.com/RedHatInsights/curiosity-frontend/issues/831)) ([e35a0b0](https://github.com/RedHatInsights/curiosity-frontend/commit/e35a0b05a60587ab42f0937bf61e226e8a375d76))
* **rhsmServices,redux:** ent-4366 tally refactor for metric id ([#822](https://github.com/RedHatInsights/curiosity-frontend/issues/822)) ([40628b5](https://github.com/RedHatInsights/curiosity-frontend/commit/40628b54ffaf64febb71ba4605b9ce4301523951))
* **rhsmServices,redux:** ent-4367 instances inventory ([#830](https://github.com/RedHatInsights/curiosity-frontend/issues/830)) ([1e42ce7](https://github.com/RedHatInsights/curiosity-frontend/commit/1e42ce72a6692730fb002789e434f85bef27f0e1))
* **toolbarFieldSla,Usage:** ent-4208 standalone sla, usage ([#820](https://github.com/RedHatInsights/curiosity-frontend/issues/820)) ([8d6dc4a](https://github.com/RedHatInsights/curiosity-frontend/commit/8d6dc4ae38a9b90cbb4b970c826949e66eb14ed3))

### Bug Fixes

* **build:** npm updates ([#767](https://github.com/RedHatInsights/curiosity-frontend/issues/767)) ([aea6114](https://github.com/RedHatInsights/curiosity-frontend/commit/aea6114b3c37605d24658ac986b7d79625f3f4ab))
* **build:** npm updates ([#801](https://github.com/RedHatInsights/curiosity-frontend/issues/801)) ([fcc5397](https://github.com/RedHatInsights/curiosity-frontend/commit/fcc5397485b9092bf52906481b48556fca29e21a))
* **build:** pf, platform npm updates ([#801](https://github.com/RedHatInsights/curiosity-frontend/issues/801)) ([42fdef2](https://github.com/RedHatInsights/curiosity-frontend/commit/42fdef23a8e9f6ab6318912e3ac653ee6621c619))
* **chartHelpers:** ent-4135 custom x, y, filter NaN and undefined ([#783](https://github.com/RedHatInsights/curiosity-frontend/issues/783)) ([d4bf025](https://github.com/RedHatInsights/curiosity-frontend/commit/d4bf025d56889c3646d82a3c6d351bceb842a764))
* **chartHelpers:** ent-4366 adjust yaxis domain for small values ([#839](https://github.com/RedHatInsights/curiosity-frontend/issues/839)) ([e6c6ccc](https://github.com/RedHatInsights/curiosity-frontend/commit/e6c6cccdaa9ec99a67fd5f5ace8bd35c9f6a25c6))
* **config:** ent-4367 rhosak config checks ([#840](https://github.com/RedHatInsights/curiosity-frontend/issues/840)) ([e6382cc](https://github.com/RedHatInsights/curiosity-frontend/commit/e6382cc47d8b66b0f529c60261632e493995ecb5))
* **graphCardHelpers:** ent-4510 allow product custom axes ([#829](https://github.com/RedHatInsights/curiosity-frontend/issues/829)) ([69484b9](https://github.com/RedHatInsights/curiosity-frontend/commit/69484b987a95fbbc320b572b187f74d4c459b05b))
* **graphCardMetricTotals:** ent-4366 daily monthly displays ([#827](https://github.com/RedHatInsights/curiosity-frontend/issues/827)) ([cc64e95](https://github.com/RedHatInsights/curiosity-frontend/commit/cc64e95b2254fc1492d3ed27763e33fa8f2ff8b6))
* **graphCardMetricTotals:** ent-4366 daily, monthly header copy ([#840](https://github.com/RedHatInsights/curiosity-frontend/issues/840)) ([9564f5b](https://github.com/RedHatInsights/curiosity-frontend/commit/9564f5bc530831c727c669bad92ba215267850ef))
* **graphCardMetricTotals:** ent-4366 data-test attributes ([#836](https://github.com/RedHatInsights/curiosity-frontend/issues/836)) ([6334272](https://github.com/RedHatInsights/curiosity-frontend/commit/633427228c23d768053bd93cfb3dcd24d875eb86))
* **graphCardMetricTotals:** ent-4366 expand data-test ([#838](https://github.com/RedHatInsights/curiosity-frontend/issues/838)) ([8e86516](https://github.com/RedHatInsights/curiosity-frontend/commit/8e865161fe7e2fe47fa8ac66ef56ad5498d3dda1))
* **graphCardMetricTotals:** ent-4366 total timestamp formats ([#840](https://github.com/RedHatInsights/curiosity-frontend/issues/840)) ([a3f8543](https://github.com/RedHatInsights/curiosity-frontend/commit/a3f854308616b8fe79dbf1fe109e2488597f8cd9))
* **helpers:** ent-4366 optional chaining for numbro ([#832](https://github.com/RedHatInsights/curiosity-frontend/issues/832)) ([5961442](https://github.com/RedHatInsights/curiosity-frontend/commit/59614427a06684ce6e9dd08ff0d7e5a76dbe3d68))
* **i18n:** ent-4251 filter undefined, empty multi-context ([#775](https://github.com/RedHatInsights/curiosity-frontend/issues/775)) ([e3ff5cb](https://github.com/RedHatInsights/curiosity-frontend/commit/e3ff5cb9723e6e7492031075123b2aa1e7449eb9))
* **locale:** ent-4251 graph string key restructure ([#775](https://github.com/RedHatInsights/curiosity-frontend/issues/775)) ([dee6275](https://github.com/RedHatInsights/curiosity-frontend/commit/dee6275b748d2c4666a1973cb00892caa6102f96))
* **locales:** ent-4367 string updates for rhosak ([#835](https://github.com/RedHatInsights/curiosity-frontend/issues/835)) ([fbddc88](https://github.com/RedHatInsights/curiosity-frontend/commit/fbddc8864d3d7345692fd5b9e68113f0c04981ef))
* **openshiftMetrics,openshiftDedicated:** ent-4251 legend tooltip ([#775](https://github.com/RedHatInsights/curiosity-frontend/issues/775)) ([8ca4bb7](https://github.com/RedHatInsights/curiosity-frontend/commit/8ca4bb7fa2cd10b5b91db612f8c517a6ee48b103))
* **productView:** ent-4247 disable take a tour header button ([#774](https://github.com/RedHatInsights/curiosity-frontend/issues/774)) ([bb6a564](https://github.com/RedHatInsights/curiosity-frontend/commit/bb6a56477eb20efb327eb8d88d368f3ede166dc8))
* **productViewOpenShiftContainer:** ent-4367 hosts inventory ([#833](https://github.com/RedHatInsights/curiosity-frontend/issues/833)) ([21e6c52](https://github.com/RedHatInsights/curiosity-frontend/commit/21e6c5207b40702fc55753245ba2ccb0e35c697e))
* **rhsmSchemas:** ent-4366 graph total display mismatch ([#837](https://github.com/RedHatInsights/curiosity-frontend/issues/837)) ([455a198](https://github.com/RedHatInsights/curiosity-frontend/commit/455a1981d02dd9a23d210d5801b3fb6d69481533))
* **rhsmServices:** ent-3352 api response props, mock and tests ([#786](https://github.com/RedHatInsights/curiosity-frontend/issues/786)) ([e17a2b7](https://github.com/RedHatInsights/curiosity-frontend/commit/e17a2b764627801ae1dec7234d8756ccec5d87ec))
* **routes:** ent-4366 rhosak product path id ([#826](https://github.com/RedHatInsights/curiosity-frontend/issues/826)) ([0700795](https://github.com/RedHatInsights/curiosity-frontend/commit/07007955702644e8654dfb74a4a3938a2ccaad78))
* **routing:** Use dynamic router basename ([#821](https://github.com/RedHatInsights/curiosity-frontend/issues/821)) ([db1751c](https://github.com/RedHatInsights/curiosity-frontend/commit/db1751c7cbea936a6962d7daf532470e7b5ff014))
* **toolbarFields:** ent-4208 left, right select positioning ([#824](https://github.com/RedHatInsights/curiosity-frontend/issues/824)) ([10fb34c](https://github.com/RedHatInsights/curiosity-frontend/commit/10fb34c304bd4957961bfa88523146f0f186ed0b))
* **useRhsmSelectors:** import cleanup ([#817](https://github.com/RedHatInsights/curiosity-frontend/issues/817)) ([81e8a06](https://github.com/RedHatInsights/curiosity-frontend/commit/81e8a06d161aee7081b7ce05da13c09412b632d8))

### Build

* **dev,proxy:** ent-3643 eslint webpack plugin ([#761](https://github.com/RedHatInsights/curiosity-frontend/issues/761)) ([29d9a69](https://github.com/RedHatInsights/curiosity-frontend/commit/29d9a693d592d71a271f51ad8430f98cd42ecc7c))

### Code Refactoring

* **graphCard:** ent-4208 activate product hooks ([#817](https://github.com/RedHatInsights/curiosity-frontend/issues/817)) ([c56f424](https://github.com/RedHatInsights/curiosity-frontend/commit/c56f424bf6a212d94e61cd2dccd71fae40fa5f8f))
* **inventorySubscriptions:** ent-4366 disable subscriptions ([#825](https://github.com/RedHatInsights/curiosity-frontend/issues/825)) ([5c1e2c6](https://github.com/RedHatInsights/curiosity-frontend/commit/5c1e2c6077b812fb0735fba8348136cf2715c340))
* **productView:** ent-4208 activate product, query context ([#814](https://github.com/RedHatInsights/curiosity-frontend/issues/814)) ([de1d9e7](https://github.com/RedHatInsights/curiosity-frontend/commit/de1d9e776b56f0ebe97452781cfd0c05bc74092d))
* **router:** ent-4208 activate routeDetail context ([#813](https://github.com/RedHatInsights/curiosity-frontend/issues/813)) ([7b20f45](https://github.com/RedHatInsights/curiosity-frontend/commit/7b20f455c1b8e80f199bedcfe789b4582d07a197))
* **toolbar:** ent-4208 activate product hooks ([#820](https://github.com/RedHatInsights/curiosity-frontend/issues/820)) ([84a3000](https://github.com/RedHatInsights/curiosity-frontend/commit/84a3000399f2662732d767fca8d340ec37e724bd))

### CODE REVIEW

**Review by mbpierce — APPROVED** [review]
lgtm

**Comment by mbpierce** [comment]
Weird... I thought I did that hours ago before I left...
Sorry I'm late!

**Review by jlprevatt — APPROVED** [review]
Reviewed main feature changes via #842, approving

**Review by mirekdlugosz — APPROVED** [review]
@mbpierce you might be thinking about #842 , which is the same set of changes, but to prod-beta. This one is prod-beta to prod.

Anyway, :ship: away

**Pull request merged**
