### PR TITLE
Draft release 1.0.0, Sync Test to Stage

### PR DESCRIPTION
**Pull request by cdcabrera**
### Features
1. **inventoryList,views** issues/10 display inventory list (#372) (5f1ca14)
1. **messageView** issues/320 app-level maintenance mode (#379) (27182b4)
1. **guestsList** issues/10 display infinite table listing (#390) (65b65f0)
1. **authentication** issues/373 use platform not authorized (#402) (713a55f)

### Bug Fixes
1. **table,tableSkeleton** issues/10 align content prop to pf (#372) (7322940)
1. **inventoryListSelectors** issues/10 itemCount, deep equals (#372) (d37ab77)
1. **graphCard,c3GraphCard** issues/10 align card component (#372) (497771c)
1. **rhsmApiTypes** issues/380 api query types (#381) (a3bc804)
1. **apiQueries,reduxHelpers** issues/380 query schema (#381) (10eea39)
1. **graphCard** issues/380 graph refresh on query (#384) (850eb65)
1. **inventoryListSelectors** issues/10 last seen date context (#382) (f3aee0e)
1. **inventoryList** issues/10 missing platform component (#385) (12b4b25)
1. **testing** platform component import exceptions (#386) (c889548)
1. **graphCard,chartArea** issues/365 increase stroke width (#392) (ef0333a)
1. **tableSkeleton** allow table with zero rows (#390) (00c001b)
1. **guestsList** issues/10 increase paging limit (#390) (7000f43)
1. **pagination** issues/400 page reset on limit update (#405) (a8a580b)
1. **openshiftView** issues/383 apply uom query filter (#408) (3b7995a)
1. **pagination,toolbar** issues/400 page reset filter update (#412) (e0517fa)
1. **guestsList** avoid boolean, remove nullish coalescing op (#413) (77ec6bd)

### Styles
1. **pageLayout** issues/391 remove gray padding (#401) (f67c60c)

### Chores
1. **rhsmServices** expand system inventory mock (#405) (a3159d1)
1. **build** expand changelog displayed commits (#415) (63a72f9)

### CODE REVIEW

**Review by jlprevatt — APPROVED** [review]
Viewed features and double-checked with @cdcabrera for any possible doc impact from the bug fixes. Approving.

**Review by ntkathole — APPROVED** [review]
ACK :+1: 

Looks good!

**Comment by cdcabrera** [comment]
We'll give the API a chance to run stand-alone over the weekend, then look at merging this into Prod-beta around the 2020-09-14

**Comment by ntkathole** [comment]
@cdcabrera could we get this in #421 ?

**Comment by cdcabrera** [comment]
Blocked until #421 can be implemented, reviewed and merged from QA branch

**Comment by ntkathole** [comment]
Issue is fixed and we are good with this release :tada:

**Pull request merged**
