### PR TITLE
Draft Release 1.6.1, Sync Test to Stage

### PR DESCRIPTION
**Pull request by cdcabrera**
## Descriptions
Draft 1.6.1 GUI release

## Notes
- This release is dependent on the API having ent-3818, ent-3888 in the prod environment

### Bug Fixes

* **authentication:** remove test block ([#691](https://github.com/RedHatInsights/curiosity-frontend/issues/691)) ([8f7c7a9](https://github.com/RedHatInsights/curiosity-frontend/commit/8f7c7a923a6a58be206cdd5581669089df2c55bf))
* **build:** npm updates ([#685](https://github.com/RedHatInsights/curiosity-frontend/issues/685)) ([3592e13](https://github.com/RedHatInsights/curiosity-frontend/commit/3592e13c107bd7057c3c43dab5bb7bfcc4e4e140))
* **i18n:** allow multi-context ([#699](https://github.com/RedHatInsights/curiosity-frontend/issues/699)) ([ba210b5](https://github.com/RedHatInsights/curiosity-frontend/commit/ba210b5786d04874a3ef85f7b9bfbedd7a3c96c2))
* **productView:** ent-3888 use meta to display total core hours ([#692](https://github.com/RedHatInsights/curiosity-frontend/issues/692)) ([ecc20fc](https://github.com/RedHatInsights/curiosity-frontend/commit/ecc20fc2174333048693160d2907ed8b4520249a))
* **productViewMissing:** ent-3913 apply platform appNavClick ([#695](https://github.com/RedHatInsights/curiosity-frontend/issues/695)) ([e2043e7](https://github.com/RedHatInsights/curiosity-frontend/commit/e2043e7facf288cb757c6a5f699d1ed15e6d7f72))
* **redirect:** ent-3833 restructure, force a path ([#695](https://github.com/RedHatInsights/curiosity-frontend/issues/695)) ([5d0f86b](https://github.com/RedHatInsights/curiosity-frontend/commit/5d0f86b2c624949e2b10e3552ae3f864c599d25a))
* **redirect:** ent-3916 route config, dynamic loading ([#691](https://github.com/RedHatInsights/curiosity-frontend/issues/691)) ([8832b0e](https://github.com/RedHatInsights/curiosity-frontend/commit/8832b0ec3e73a84b59fa9fdd743a3bd07ef8ff08))
* **routes,router:** ent-2745 dynamic lazy load views ([#679](https://github.com/RedHatInsights/curiosity-frontend/issues/679)) ([7c3b4bc](https://github.com/RedHatInsights/curiosity-frontend/commit/7c3b4bcd7182168abab5c60b29a181a6444378ba))
* **select,toolbarFields:** ent-3879 apply test attributes ([#687](https://github.com/RedHatInsights/curiosity-frontend/issues/687)) ([bc1b64c](https://github.com/RedHatInsights/curiosity-frontend/commit/bc1b64c2557016bd9df714701cb8843ebd234ea6))
* **testing:** mock window location, components with hooks ([#680](https://github.com/RedHatInsights/curiosity-frontend/issues/680)) ([6e4d538](https://github.com/RedHatInsights/curiosity-frontend/commit/6e4d5384ecd365039660617149af3e27b2a14f0e))
* **testing:** outside src import, unit test locale ([#680](https://github.com/RedHatInsights/curiosity-frontend/issues/680)) ([ca38f5c](https://github.com/RedHatInsights/curiosity-frontend/commit/ca38f5c7cf03ffe12be8e8f91b3adef6520bb958))

### Code Refactoring

* **config:** ent-2745 consolidate nav, routing configs ([#656](https://github.com/RedHatInsights/curiosity-frontend/issues/656)) ([a8667a9](https://github.com/RedHatInsights/curiosity-frontend/commit/a8667a9885b3737ad6b08abc627c213813550824))
* **productViewMissing:** ent-2745 use route helper ([#656](https://github.com/RedHatInsights/curiosity-frontend/issues/656)) ([4fe3d8c](https://github.com/RedHatInsights/curiosity-frontend/commit/4fe3d8c5653fbb3279af04061934cd8f0eb64780))
* **router:** ent-2745 convert class component ([#656](https://github.com/RedHatInsights/curiosity-frontend/issues/656)) ([8ed0445](https://github.com/RedHatInsights/curiosity-frontend/commit/8ed044556222c32c75d27c2103891798a51495ef))
* **router:** ent-2745 function, hook convert ([#684](https://github.com/RedHatInsights/curiosity-frontend/issues/684)) ([d43932a](https://github.com/RedHatInsights/curiosity-frontend/commit/d43932a5ca29e2f7c7740b1cb3e2ff012c639203))
* **routerHelpers:** ent-2745 consolidate nav, route lookup ([#656](https://github.com/RedHatInsights/curiosity-frontend/issues/656)) ([475eed1](https://github.com/RedHatInsights/curiosity-frontend/commit/475eed1b86c0102592620618e139274ee2f2bcb0))

### CODE REVIEW

**Comment by mirekdlugosz** [comment]
> * **productView:** [ent-3888](https://issues.redhat.com/browse/ENT-3888) use meta to display total core hours ([#692](https://github.com/RedHatInsights/curiosity-frontend/issues/692)) ([ecc20fc](https://github.com/RedHatInsights/curiosity-frontend/commit/ecc20fc2174333048693160d2907ed8b4520249a))

Can we do it already? I See ENT-3818 is not yet deployed to prod. And if backend is not deployed first, there will be no "core hours" label at all, which would be a regression from user point of view.

Otherwise, these changes look fine.

**Review by jlprevatt — APPROVED** [review]
No objections from docs side after the blockers are cleared.

**Comment by cdcabrera** [comment]
@mirekdlugosz you are correct we're delaying this PR until "total core hours" is moved to prod on the API side

**Review by mirekdlugosz — APPROVED** [review]
Since ent-3818 has been deployed to prod recently (I can see `total_core_hours` in meta of tally OpenShift-metrics response), I believe we can go ahead with deployment of this.

**Pull request merged**
