### PR TITLE
chore(build): run QE tests during PR workflow

### PR DESCRIPTION
**Pull request by mirekdlugosz**
The main goal is to run QE tests on ephemeral environment as part of PR workflow.

Right now there's one such tests that goes to subscription table and verifies it is not displayed. Later we will figure out how to create data inside ephemeral env, and we'll work on extending suite of tests.

I've got this running when issuing commands manually from my machine. Let's see if I can get it running from PR check as well.

### CODE REVIEW

**Comment by mirekdlugosz** [comment]
OK, so this passed. If you go to "details" under ci.int.devshift.net PR build and log in, you can click "Test Results" and see breakdown of tests that were run. Which is nice.

I am pretty sure accessing ci.int.devshift.net requires VPN.

Some time breakout of this specific run:

- running unit tests, building container, pushing it to quay: 02:49
- deploying new ephemeral environment with subscriptions, including backend and dependencies: 10:31
- deploying pod with QE tests and running them: 02:06
- the whole thing: 16:08

GitHub tells me GitHub action took 8 minutes, so App SRE workflow doubles that.

For the reference, backend team needs around 20 minutes to complete their PR job on App SRE infra. We'll probably need a little more, because UI tests are always going to be slower than API. Obviously I don't want to make that too slow, I think 25 minutes is reasonable, 30 minutes is absolute maximum. We will have to cut the scope of UI tests to meet this time requirement - we will run fewer tests than backend team does.

**Comment by cdcabrera** [comment]
@mirekdlugosz would removing the redundancy of running the GUI tests make much of a difference (removing the [`$ yarn test:ephemeral` and related node scripts in `package.json`](https://github.com/RedHatInsights/curiosity-frontend/blob/main/package.json#L58))? 

If we haven't already removed the redundant unit test checks, It would be preferable if we could and focus on just QE's facet.

Most of it is we still use GitHub actions for
- not having to login to review unit test results on a public project
- codecov aspect of actions, unclear if this support works or is even provided with the behind-the-scenes checks. we generate the coverage, just unclear where it goes?
- a more in-depth aspect of dev integration checks. we had to disable parts of those checks to get them to pass for the behind-the-scenes checks
- commit linting
- and generally just easier to find documentation =)

**Review by cdcabrera — APPROVED** [review]
Posted a non-blocking question/comment. Just need a rebase and we should be good

**Comment by cdcabrera** [comment]
As of 20221130 holding PR. It's recommend we hold until there are more tests associated with this check

**Comment by san7ket** [comment]
Closing this in favor of https://github.com/RedHatInsights/curiosity-frontend/pull/1072

**Pull request closed without merging**
