### PR TITLE
Production Release 1.6.1

### PR DESCRIPTION
**Pull request by cdcabrera**
### Bug Fixes

* **authentication:** remove test block ([#691](https://github.com/RedHatInsights/curiosity-frontend/issues/691)) ([949195d](https://github.com/RedHatInsights/curiosity-frontend/commit/949195d44b5dfd2bbe63909846b872ddf394ae79))
* **build:** npm updates ([#685](https://github.com/RedHatInsights/curiosity-frontend/issues/685)) ([646e3eb](https://github.com/RedHatInsights/curiosity-frontend/commit/646e3eb9e8ed061c608c69b24cdd0c0df7a05ffa))
* **i18n:** allow multi-context ([#699](https://github.com/RedHatInsights/curiosity-frontend/issues/699)) ([b653519](https://github.com/RedHatInsights/curiosity-frontend/commit/b6535194c56c9693fc35551682b1925a9be1f001))
* **productView:** ent-3888 use meta to display total core hours ([#692](https://github.com/RedHatInsights/curiosity-frontend/issues/692)) ([84fc978](https://github.com/RedHatInsights/curiosity-frontend/commit/84fc978061c46f263dd65cc2a2e755f0d32c335d))
* **productViewMissing:** ent-3913 apply platform appNavClick ([#695](https://github.com/RedHatInsights/curiosity-frontend/issues/695)) ([00436b3](https://github.com/RedHatInsights/curiosity-frontend/commit/00436b3750ed6d7f59863458279fb106bfdc0525))
* **redirect:** ent-3833 restructure, force a path ([#695](https://github.com/RedHatInsights/curiosity-frontend/issues/695)) ([b39c929](https://github.com/RedHatInsights/curiosity-frontend/commit/b39c9298ed97ebacc5f1b1835737a619599d1533))
* **redirect:** ent-3916 route config, dynamic loading ([#691](https://github.com/RedHatInsights/curiosity-frontend/issues/691)) ([9fde0e4](https://github.com/RedHatInsights/curiosity-frontend/commit/9fde0e4c38a84bf5a3a62142e8041dfd41793394))
* **routes,router:** ent-2745 dynamic lazy load views ([#679](https://github.com/RedHatInsights/curiosity-frontend/issues/679)) ([642fa1d](https://github.com/RedHatInsights/curiosity-frontend/commit/642fa1d786ae5fda214948bef3aca9de0a6ebbbf))
* **select,toolbarFields:** ent-3879 apply test attributes ([#687](https://github.com/RedHatInsights/curiosity-frontend/issues/687)) ([d8809f4](https://github.com/RedHatInsights/curiosity-frontend/commit/d8809f4639e754dfbbb8da1f3723b0b54572e957))
* **testing:** mock window location, components with hooks ([#680](https://github.com/RedHatInsights/curiosity-frontend/issues/680)) ([72f161a](https://github.com/RedHatInsights/curiosity-frontend/commit/72f161a718e088325eb8334616a6371a7e151481))
* **testing:** outside src import, unit test locale ([#680](https://github.com/RedHatInsights/curiosity-frontend/issues/680)) ([1a4e8de](https://github.com/RedHatInsights/curiosity-frontend/commit/1a4e8deda29d243e5ae997e5bee1e1abbe5ae7f9))

### Code Refactoring

* **config:** ent-2745 consolidate nav, routing configs ([#656](https://github.com/RedHatInsights/curiosity-frontend/issues/656)) ([3fc7d89](https://github.com/RedHatInsights/curiosity-frontend/commit/3fc7d89ca038b31cb3ac44f60f435e9f603c2951))
* **productViewMissing:** ent-2745 use route helper ([#656](https://github.com/RedHatInsights/curiosity-frontend/issues/656)) ([dfe8502](https://github.com/RedHatInsights/curiosity-frontend/commit/dfe85026a69919794e15400fd74261bc7e22c786))
* **router:** ent-2745 convert class component ([#656](https://github.com/RedHatInsights/curiosity-frontend/issues/656)) ([f6901a5](https://github.com/RedHatInsights/curiosity-frontend/commit/f6901a574cc64503cfc077c7d98829b9d9b5f429))
* **router:** ent-2745 function, hook convert ([#684](https://github.com/RedHatInsights/curiosity-frontend/issues/684)) ([a2900b7](https://github.com/RedHatInsights/curiosity-frontend/commit/a2900b7475a174934558cd7395a7815a402195e2))
* **routerHelpers:** ent-2745 consolidate nav, route lookup ([#656](https://github.com/RedHatInsights/curiosity-frontend/issues/656)) ([d64a90f](https://github.com/RedHatInsights/curiosity-frontend/commit/d64a90fd9acc60e2ef8eec7a399ca0bf24971457))

### CODE REVIEW

**Comment by cdcabrera** [comment]
There is a possible known issue related to the fix we performed for #692 ENT-3888 that has to do with a "truthy" condition on the value. It is recognized this will not show `0 core hours used`. 

We'll review adding this display back in the proposed future release 1.7.0

**Review by mirekdlugosz — APPROVED** [review]
Looks good to me. Ship it at your convenience.

**Comment by bclarhk** [comment]
If `0 core hours used` is hidden, that's ok. If there’s no usage, there’s no usage. The user isn’t going to care because they don’t use it…

**Comment by jlprevatt** [comment]
RE the core hours used issue, I changed the doc statement to say:
"A cumulative **core hours used** value also displays for the most recent snapshot of the usage for that month _if there is accumulated usage to display_." (where italics = the new part)

**Pull request merged**
